language:  generic
node_js: 
  - "stable"

branches:
  only:
    - master

cache:
  directories:
    - "node_modules"

dist: xenial

script:
- echo "skipping tests"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true