language: node_js
node_js: 
  - "stable"

branches:
  only:
    - master

cache:
  directories:
    - "node_modules"
    
script:
- echo "skipping tests"

deploy:
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true